// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFNnlufuYmLU_FuGXak_Dq9EFqaAS6oU4',
    appId: '1:912485216345:web:864eb551933bb3d98e4148',
    messagingSenderId: '912485216345',
    projectId: 'flutter-de85c',
    authDomain: 'flutter-de85c.firebaseapp.com',
    storageBucket: 'flutter-de85c.appspot.com',
    measurementId: 'G-27E7JYY207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPcx7HhBrsMzmaupaFZ2eh9aG4nCMd0A',
    appId: '1:912485216345:android:3a8046edbeb4a1f18e4148',
    messagingSenderId: '912485216345',
    projectId: 'flutter-de85c',
    storageBucket: 'flutter-de85c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB99LHmhY42Thc76VItNBk9Eq4ICUAKZSE',
    appId: '1:912485216345:ios:19e64e09f329debe8e4148',
    messagingSenderId: '912485216345',
    projectId: 'flutter-de85c',
    storageBucket: 'flutter-de85c.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB99LHmhY42Thc76VItNBk9Eq4ICUAKZSE',
    appId: '1:912485216345:ios:19e64e09f329debe8e4148',
    messagingSenderId: '912485216345',
    projectId: 'flutter-de85c',
    storageBucket: 'flutter-de85c.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFNnlufuYmLU_FuGXak_Dq9EFqaAS6oU4',
    appId: '1:912485216345:web:0c25e01acc672b9f8e4148',
    messagingSenderId: '912485216345',
    projectId: 'flutter-de85c',
    authDomain: 'flutter-de85c.firebaseapp.com',
    storageBucket: 'flutter-de85c.appspot.com',
    measurementId: 'G-QXX2F2461S',
  );
}
